### ISSUE TITLE
wiki 관련 웹훅이 전달이 안 되는 문제

### ISSUE THREAD

**Issue by RE-A** [Capstone-R-99/BubbLit#1]
사실 이건 안되도 기능엔 지장없는데, 일단 문제가 생겼어서 올림. 
아마 전에도 계속 안 됐던 거 같음.

일단 settings -> webhook 에서 웹훅을 설정할 수 있고, 목록 중 마지막이 이슈&위키 관련 웹훅임.

![image](https://user-images.githubusercontent.com/11948404/77768531-f1eca300-7085-11ea-82c1-8a58af4ddd71.png)

 이 상태로 설정해놨는데, 이슈의 경우는 전송이 잘 되지만 위키는 전송이 하나도 안 되고 있음.

설정 페이지에서 아래로 내려보면 다음과 같이 전송 로그를 볼 수 있는데, 모두 전달이 잘 되고 있음. 심지어 응답도 잘 받고 있는데 디스코드쪽 문제일수도?

![image](https://user-images.githubusercontent.com/11948404/77768869-717a7200-7086-11ea-8bf9-ee53a7226f10.png)

**Comment by RE-A** [comment]
이슈 제대로 업데이트 함.

**Comment by RE-A** [comment]
웹훅 전송 테스트

**Comment by RE-A** [comment]
테스트

**Comment by RE-A** [comment]
일반 계정에서 organization으로 옮겨가면서 문제가 생긴건가?..

**Comment by RE-A** [comment]
고쳐졌나 테스트

**Comment by pula39** [comment]
일시적인 현상이었음. 해결되었습니다.
