### ISSUE TITLE
채팅방 이름에 한글 + 띄어쓰기 넣으면 Presence 터짐

### ISSUE THREAD

**Issue by pula39** [Capstone-R-99/BubbLit#12]
가상회의에서 발견

**Comment by RE-A** [comment]
해결 방법:
channel을 만들 때 따로 parameter로 room_name:"문자열" 같은 식으로 담는다.
채널 이름(채팅방 제목)은 중복을 허용해야 할 것 같아서, 채널 이름을 제목으로 쓰는 건 부적절해 보임.

어느 집단에서 "회의방" 이라는 제목으로 이름을 만들어서 다른 데서 "회의방"이라는 채팅방 제목을 못 쓰는것도 말이 안 된다고 생각함.
그래서 채널 이름은 room ID 처럼 쓰는게 맞다고 봅니다.

**Comment by pula39** [comment]
@RE-A 그래도 예외처리하고 원인분석은 필요할거같아서 함 봐볼게용

**Comment by pula39** [comment]
확인이 귀차너...

**Comment by RE-A** [comment]
응 잘됨~~
![image](https://user-images.githubusercontent.com/11948404/83419699-71209d80-a460-11ea-91f6-8efae605da3b.png)
