### ISSUE TITLE
4/8 회의 내용

### ISSUE THREAD

**Issue by Kynel** [Capstone-R-99/BubbLit#14]
#16  -> '엄격한 회의모드' 이용에 설득이 되지 않는다
                 엄격한 회의모드를 쓸 정도의 상황에 채팅으로 회의를 할까?
                 컴퓨터, 타블렛을 지원한다고 했는데 사용성에 문제가 많다

### 1. 어플리케이션의 방향성 고찰
 -  **소수의 인원** 이 모여서 사용할 수 있는 채팅 톡방
 -  **주제와 목표를 가지고 있는 간단한 회의** 에서 편리하게 사용할 수 있다.
 - 필요성(사진 자료) - 강의중, 실시간으로 팀원의 의견을 공유하고 있는 상황
![image](https://user-images.githubusercontent.com/47177212/78799624-55b38c00-79f5-11ea-997f-c4d67b66ce6d.png)

 - 위에서 보다시피 세명의 화자가 맥락상 자신의 발언을 이어가지만, 알아보기 힘들다
 - 우리의 어플리케이션은 위와 같은 상황에서 **자신과 타인의 발언을 분리, 정리**해준다.

### 2. 우리의 어플리케이션의 차별성
 - Do you know SLACK?
 - 실제 현업에서 사용하고 있는 메신저이다.
   - 사적메신저와 업무용메신저의 분리
   - 단톡방에서 모든걸 다 한다면 잡담이랑 업무대화가 섞여서 나중에 기록찾기도 힘들고
   - 채널을 만들어서 각 주제에 따라 만들어 대화할 수 잇음, 사안별로 대화가 분리돼서 보기 편해짐
   - 카카오톡은 삭제도 불편하고 수정기능은 아예 없고, 파일보내는건 그냥 부가기능일 뿐이지 주 기능이 아니라서 여러가지 제약이 많음, 슬랙은 파일 보내는 것을 본격적으로 지원한다
   - 특정 채널은 어떨때만 알림이 오게 한다 이런 업무에 필요한 기능들이 잘 구비됨
   - 서드파티 지원이 빠방함, 깃, 구글드라이브 익스텐션레벨 지원 따로 킬 필요없음
   - 가벼움, 이용자들이 필요한 기능만 쏙쏙 제공할 수 있음(우리가 궂이 만드는 이유?)

### 3. 어플리케이션의 방향성에 맞는 부가적 기능 추가
 - 우선 어플리케이션의 필요성에 대하여 이용자들에게 설득할 수 있는 기능이 필요하다
 - 소규모 회의에서 편리하게 사용할 수 있는 기능들을 추가하여 제공할 예정
   - 실시간으로 동영상을 방에 있는 사람에게 공유
   - 이모티콘 송신
   - 참가자들이 동시에 수정, 확인할 수 있는 Board 제공
     - 브레인스토밍, 마인드맵, 투표, 이미지 공유 등
     - 그림판 비슷하게 프로토타이핑 할 수 있는 툴 제공(할수 있으면)    

### 4. 부가적 기능(추가중)
 - 그때그때 발언에 중요도, 문맥 처리를 하여, 회의가 종료된 뒤 정돈된 로그를 사용자에게 제공

### 5. 이용 시나리오
 - ppt애니메이션을 이용하여 제공해볼 예정, 우선 말로 설명한뒤 구현
 - 카톡, 슬랙, 디스코드, bubbLIT을 비교
 - 먼저 셋이서 모여서 워존 플레이를 하는 경우 어떤걸 선택?          -> Discord
 - 셋이서 서로 이모티콘&선물보내며 생일축하할때 어떤걸 선택?   -> 카톡
 - 회사 또는 동아리에서 쓸 수 있는 공식 메신저가 필요할떄?-         -> SLACK
 - 팀플이 잡혀서 모여서 떠들어야되는데...... 어디서하지..?               **-> 버블릿!!**

**Comment by pula39** [comment]
#20 에서 진행합니다
