### ISSUE TITLE
프로토타입 제작

### ISSUE THREAD

**Issue by RE-A** [Capstone-R-99/BubbLit#15]
- [x] 각 사람마다 고정된 위치에 채팅 띄우기
- [x] 왼쪽에 이미지 아무거나 넣기

------

* 현재 난관 : 각 사람마다 고정된 위치에 채팅 띄우기 -> 개개인이 구분이 되어야 한다. 개인 ID를 발급해야 한다. 어떻게?

1. 소켓 성립 단계에서 ID 부여
    - 이 경우, socket.js를 파라미터를 넣어서 채널 연결시에 사용할수 있도록 리팩토링 해야함.
2. 채널 성립 단계에서 ID 부여
    - 실제 개발시에는 이렇게 하면 안 될 듯?

&nbsp;&nbsp;

### 개인별 ID

- 현재 프로토타이핑 중이므로, 그냥 presence에서 기본으로 제공하는 phx_ref를 ID처럼 사용하기로.

![image](https://user-images.githubusercontent.com/11948404/78812005-b3e86b00-7a05-11ea-8880-a8980b5b5937.png)

이 안에 array 형태로 참여자들의 고유 번호가 들어있다. 그런데, 이 값들은 개인 ID로 쓰기엔 무리가 있다. online_at은 단순히 채널에 들어온 시간(구독한 시간이 아님), phx_ref는 피닉스 프레임워크 내부에서 사용하는 소켓간의 구별을 위한 번호 같은데, 이 값을 서버단에서 어디서 불러와서 어떻게 처리해야 할지 감이 안 잡혀서 보류.

Q. 왜 `['']` 같은게 들어가죠?

A. 나도 모름. 키 값을 말 그대로 저렇게 공백으로 주니까 씀.

주어진 값을 ID로 쓰기 너무 어렵다.
**이 방법은 폐지.**

대신, 매우 간단하면서 무식한 해결책이 있음.
![image](https://user-images.githubusercontent.com/11948404/78827196-b1920b00-7a1d-11ea-85db-384cd9a970a3.png)
메세지 보낼 때 자기 닉네임도 같이 보내고 닉네임도 브로드캐스팅 해주면 됨.

&nbsp;&nbsp;

### 이미지 불러오기 문제

 이미지를 추가하려고 하는데 import나 require문을 사용한 방법 모두 안 됨.
문제는 webpack에 있었음. 이미지 형식을 처리해주는 모듈이 설정이 안 되어 있어서 생긴 문제.

webpack-config에 url-loader 관련 옵션 추가(여기다가 이미지 관련 확장자 싹 추가해야 됨. 지금은 다 되어 있는데 혹시 빠진 게 있을 수도 있음)하고, import 문으로 이미지 path로 가서 불러오니까 됨.

![image](https://user-images.githubusercontent.com/11948404/78822260-c4084680-7a15-11ea-8dd4-a112d5952c66.png)

webpack을 통해 일괄적으로 묶는 과정을 거치기 때문에, 앞으로도 여기에 없는 확장자들은 오류가 날 것임. 참고.

-------------

Prototype이라는 브랜치로 작업내용 푸쉬 완료.

**알려진 문제점**

- 중간에 들어온 다른 사람은 기존 채팅 로그 안 보임
- 5사람 이상 들어오면 무슨 일이 일어날지 모름. 아마 오류가 나거나 가장 오래있던 사람이 채팅을 쳐도 아무도 못 보게 될 것임.
- FHD 전체화면 스크린에 최적화 됨. 일단 css를 %로 잡아놓긴 했는데, 전부 절댓값 좌표로 때려넣어서 다른 화면에서 어떻게 보일 진 책임 안 짐.
- 솔직히 부끄러울 정도의 막가파식 하드코딩이라 여기서 얻은 내용 정리만 하고 아마 코드는 날릴 거 같음.

**Comment by pula39** [comment]
@pula39 읽고 닫겠습니다
@Kynel 읽고 닫겠습니다

**Comment by pula39** [comment]
할만큼 진행해서 다른 일감에서 계속하고있다
