### ISSUE TITLE
#14 스케치업에 대한 피드백을 받습니다

### ISSUE THREAD

**Issue by Kynel** [Capstone-R-99/BubbLit#16]
![image](https://user-images.githubusercontent.com/47177212/78880034-b8f1fc80-7a8f-11ea-8657-52830e710bff.png)
### 피드백 부탁드립니다.
사소한것, 추가 & 수정하고싶은 부분, 이렇게하는거 아닌데... 등 무조건적인 피드백 요망!
1. PPT에 관한 피드백

* * *
### 이런게 있으면 좋겟다 하는 시나리오
1. **갑**, **을**, **병**은 학점 떡상의 꿈을 꾸며 셋이서 조별과제를 준비한다.
2. 첫 회의 전, 조장 **갑**은 아무 계획없이 모이게 되면 만남이 너무 늘어질것같다고 생각하여 버블릿이라는 앱의 초대링크를 세명에게 보낸다. #19 
3. 저녁식사 후, 따듯한 물로 샤워를 하고 **갑**은 아무부담없이 크롬을 켜고 버블릿에 접속한다.
4. **갑**을 기다리고있던 **을, 병**은 채팅방에서 요번분기 신작 애니 오프닝을 함께 유튜브로 보며 잡담을 하고있었다.
5. **갑, 을, 병**은 잠깐 애니이야기로 이야기를 꽃피우다 슬슬 미팅를 시작한다.
6. 버블릿에 떠있는 **유튜브를 꺼버리고, 보드를 켠다**.
7. 캡스톤의 주제를 **자유롭게 이야기하며**에서 세명에게 공유된 **BOARD**를 자유롭게 수정하며, 자신이 생각했던 주제를 펼치고, 리스트를 추린다.
8. 그 **결과를 이미지파일로 만들어 공유**한다.
9. 주제가 결정되어서, 그에대한 자신의 의견을 **BOARD의 문서기능**을 이용하여 셋이서 동시에 자유롭게 구상한다.
10. 세명은 내일 회의에서 결정해야 할 내용을 버블릿의 **TODO**기능을 활용해 정리하고, 미팅을 정리한다.
10-1.그곳에 내일에 회의에서 만나기 전까지 무엇을 해둘지, 만나고 나서 무엇을 할지를 적는다.
11. 세명은 버블릿을 활용한 시간이 알찬 시간이었다고 생각하며 미팅을 끝내고, 계속 잡담을 한다.
12. 다음날, 세명은 카페에서 모여서 버블릿에 정리된 자료로 회의를 진행한다.
-------------------------------------------------------------------------------------------
12-1. 정리된 자료를 시각적으로 표현

14. 팀장인 **갑**은 다음주까지 제출해야 할 보고서를 작성하기 시작한다.
15. 토론이 길어졌지만, 버블릿의 채팅로그 기능을 활용하면, 시간대별로 사용자들이 한 말과 제안들을 한눈에 알아볼 수 있다.
16. 그리고 **채팅방의 보관함 메뉴에서 아까 작성한 이미지파일, 문서를 컴퓨터에 저장**하여 보고서의 초안을 만들기 시작한다.
* * *

**Comment by pula39** [comment]
보니까...

## 기획 파-트
 - 결국 회의를 하긴 한다...? (엄격하고 무거운게 아니지만?)
 - 그 외에는 저는 이걸 최소스펙이라 생각하고 있었기에 좋은 것 같고 찬성입니다. (다른 기능을 넣어도 이것만 되면 좋겠어요)
  - 이러면 커스터마이즈 기능 빼고 파워울트라채팅앱으로만 가는건가?
    - 그렇다면 채팅 히스토리 보관 기한도 제한 둘 수 있어서 장기 서비스에 유리할듯?
    - 이 이야기는 캡이랑 좀 떨어져서 우리가 계속 서비스를 한다할때?

## 기능 파-트
 - TODO 기능이 추가된 것 같음.
 - 채팅방의 보관함 메뉴 기능이 추가된거같음
 - `보드를 켠다` 기능은 추가...인가? 이전에 제가 말한대로 외부 시스템 지원? 
   - 공유보드를 탭으로 지원하는 느낌? 탭 바꿔도 페이지 유지되면 좋을거같다.

## 사족
 - 모바일 대응을 생각하면, 왼쪽의 보드 부분을 끄는것도 고려?
   - `그 유사사이트`는 세로로 세워주고 있음
   - 모바일은 언제까지나 Sub임을 고려하면 될듯. 
     - 데스크탑 레이아웃 기반인데 모바일에서도 사용해주게 하는 사이트처럼?

**Comment by Kynel** [comment]
다양한 시스템을 제공하는 시스템을 만드는 것이 아닌, 특정 상황에서 유용하게 사용할 수 있는 포커스된 어플리케이션을 제공하는 것으로 방향성을 수정하였습니다.

**Comment by pula39** [comment]
#20 에서 진행합니다
