### ISSUE TITLE
4/10 할 일

### ISSUE THREAD

**Issue by RE-A** [Capstone-R-99/BubbLit#18]
1. 임형준:
    - [x] PPT 제작하기
2. 권준혁
    - [ ] DB 코딩
    - [x] 집단적 독백, 메신저 관련 논문 찾아보기 -> #17 에서 합니다
    - [x] 시나리오에서 기능 추리기 -> 아래 코멘트
    - [x] 일정 차트 다시 만들기
3. 송준호
    - [x] 프로토타입 #16 에 나온것처럼 UI 바꿔보기.
    - [x] **제작한 기능을 테스트해볼 수 있는 라이브 서버 제작**

**Comment by pula39** [comment]
## 시나리오에서 본 기능

|                    |                                   프론트엔드                                   |                                 백엔드                                | 외부기능 대체가능 여부 |
|:------------------:|:------------------------------------------------------------------------------:|:---------------------------------------------------------------------:|:----------------------:|
|       탭 추가      | 탭 클릭하면 그 탭의 내용을 표시 탭 기능별 구현 (iframe 탭이면 표시... 이런거?) | 현재 탭 브로드캐스팅 각 탭의 정보 브로드캐스팅 탭의 정보를 저장해야함 |            X           |
|        보드        | 그리게 해줘야함 쓰게해줘야함                                                   | 그린 정보를 실시간 동기화 서버에 저장                                 |      O (구글독스)      |
|     TODO 리스트    | 체크 가능 편집 가능                                                            | 체크. 편집 정보를 동기화 서버에 저장                                  |  O (있을것 같...은데?) |
|     iframe 기능    | iframe 표시                                                                    | iframe 정보 동기화                                                    |  - (애초에 외부기능임) |
| 이미지로 저장 기능 | 왼쪽의 창을 이미지로 저장하게 함                                               | X                                                                     |            X           |

**Comment by pula39** [comment]
히ㅣㅎ 디비못함
