### ISSUE TITLE
메신저를 여러개 사용할 때의 거부감에 관한 자료

### ISSUE THREAD

**Issue by Kynel** [Capstone-R-99/BubbLit#19]
https://www.google.com/amp/s/cm.asiae.co.kr/ampview.htm%3fno=2017082108514649257
카톡으로 버블릿의 초대링크를 보낸다 라는 항목에 추가하는 것에 대한 의견이 필요함다.

**Comment by pula39** [comment]
기사에서 잡는 포인트는 `사생활 노출`때문이라 핀트가 좀 다른것 같긴 하네용

**Comment by pula39** [comment]
>모바일 메신저 앱 선택에는 '주변사람들의 이용 정도'(78.9%)가 작용하는 것으로 나타났다. '익숙해서'(46.6%), 'PC버전과 호환이 좋아서'(25.1%) 등도 이유로 꼽혔다.

후...

**Comment by Kynel** [comment]
>우선 2개의 메신저를 이용한다는 사람이 37.2%로 가장 높았으며 1개만을 쓰는 이용자는 36.3%였다. 3개 이상 사용하는 사람의 비중은 21.2%였다. 전년 대비 4.3%포인트 증가, 가장 많은 변동이 있었다. 
이부분 약간 tmi인가요?

**Comment by pula39** [comment]
@Kynel  많은 메신저를 쓰는 이유가 사생활 노출때문이라서요... 같은 통계 정보인데 다른 이유를 드는 조사결과가 있으면 좋겠네요 (예를 들어 한 개의 메신저가 모든 기능을 지원 못해서 여러개쓴다 그런?)

**Comment by Kynel** [comment]
@pula39 네 그부분에 중점을두고 찾아보겠습니다 : )

**Comment by pula39** [comment]
일단 5번쨰주 (4월 14일)에는 안하는걸로

**Comment by pula39** [comment]
할만큼 조사했다
