### ISSUE TITLE
#23 작업

### ISSUE THREAD

**Issue by pula39** [Capstone-R-99/BubbLit#24]
후
 - [x] 유저 테이블 생성
 - [x] 채팅로그 테이블 생성
 - [x] 세션에 유저 아이디 저장을 한다
 - [x] 세션의 유저 아이디를 기반으로 채팅 로그를 기록한다
 - [x] 클라가 요구하면 채팅 데이터를 내려준다.

**Comment by pula39** [comment]
계정 만들고 비번 암호화

https://medium.com/innoventes/user-authentication-phoenix-1-4-ebda68016740

**Comment by RE-A** [comment]
혹시 여기서 말하는 암호화가 비밀번호 해쉬화면, 그냥 프론트에서 해쉬화해서 던져줄까요?

**Comment by pula39** [comment]
@RE-A 비밀번호 해쉬화 맞음. 프론트에서 암호화를 하는게 맞는진 모르겠다. 그러면 프론트 패킷 해킹하면 비번 뚫리는거라. 

리눅스에서는 문제 없다고 알고이씀. aws 올리면서 확인해주면 ㄳ ㅎ;;

**Comment by RE-A** [comment]
이거 위에 나온 링크대로 했는데 여전히 nmake를 못찾아서 컴파일이 안 됨.
2017 지우고 2019 깔고 그랬어서 뭔가 꼬인거거나, 해당 방법이 2019에서 지원이 안 되는건지는 잘 모르겠음.

https://github.com/riverrun/comeonin/wiki/Requirements

공식 윈도우즈용 빌드법 보고 따라하는 중이고 되면 결과 따로 쓰겠음.

**Comment by pula39** [comment]
# 어? 날먹 아닌데?

슬슬 `백엔드란 무엇인가`에 대한 감이 잡혀가는것같기도 하다.
세션, 소켓, 메시지라는 것에 대해 알아야하고, 인증을 결국 Token 써서 해야한다.

# 용어 (Domain ㅎ) 정리
 - 토큰 : 무엇을 식별할 수 있는 무언가
 - 소켓 : 통신의 논리적 단위
 - 세션 : 한 통신이 이루어지는 모든 것. 세션 안에는 소켓 수립이 포함되어있다.

# 세션은 왜 생김?
 - 이전의 유산임
 - HTTP1.0은 한번 뭘 처리할 때 마다 소켓을 끊음
 - 세션은 이런 물리적인 단위가 아니라 논리적인 단위임. 실제 소켓이 중간에 끊기든 말든, 우리가 그 사이에 연결되어있다 생각하면 연결되어있는거임...
 - 그래서 이 연결을 식별하기 위해서 세션 ID라는 것을 통해, 그 논리적 세션이 계속 이어져있는지 확인한다.
 - 그러니까 세션은 `소켓 열고 닫히는거랑 원래는 무관함!`

# 근데 세션이랑 소켓이랑 비슷하게 움직이는 것 같은데?
 - 그것은 HTTP1.1에서 소켓을 재활용할 수 있게 되었기 때문임.
 - 그래서 소켓을 한번 열어두고 계속 씀.
 - 그래서 보통 세션이 끝나면 소켓을 닫음.
# 그럼 필요없는거  아님?
 - 그건 아님.
 - 우리가 인터넷 서핑을 할 때 ,인터넷 연결을 끊고 다른 회선으로 이어서 해도 잘 되는것은 세션이 유지되기 때문임.
 - 중간에 소켓은 끊어졌을 것임. 그래서 세션은 여전히 그 역할을 다하고 있음.

# 소켓에서 Auth를 해보자
토큰을 통해서 auth를 해야함.
> Plug.Conn is not available in Phoenix.Channel. Channels rely on Phoenix.Socket instead and you can use Phoenix.Token for authentication.
>Here's a tutorial on how to authenticate channels in Phoenix. (링크짤)

>Perfect answer. It is also important to point out that accessing the session on channels would be unsafe as websocket sessions are vulnerable to cross-origin attacks.

(https://stackoverflow.com/questions/34446712/in-elixir-phoenix-how-to-get-session-in-other-module-as-a-module-use-phoenix-c 에서 인용)

나는 이 글을 참고하면서 할 예정임.
역시 날먹은 안되는구나. 많이 배워간다.
https://timber.io/blog/building-a-real-time-app-with-phoenix/#part-i-real-time-text-editing-with-phoenix-channels

**Comment by RE-A** [comment]
![image](https://user-images.githubusercontent.com/11948404/79680379-edad4300-8249-11ea-9fa8-082dfa0514f7.png)

 로그인 성공함.
bcrypt_elixir는 msvc의 nmake를 이용해서 빌드를 함. 이 nmake는 마이크로소프트판 make라고 보면 될 듯. 엘릭서에서 이 라이브러리 컴파일을 할 때 nmake로 c 코드들을 컴파일 하는데, 이 nmake 관련 설정에 문제가 있었음. 

 일단 기본적으로 nmake가 있는 폴더를 환경 변수에 추가해야 하고, 비주얼 스튜디오 폴더에, 환경 세팅관련 배치 파일(vcvarsall.bat)이 있는데 그걸 통해 환경이 세팅된 상태로 컴파일을 해야 정상적으로 작동됨. 그런데 이 배치파일을 실행시켜도 컴파일하면 인클루드 첫줄부터 stdio.h를 찾을 수 없다고 오류가 남.

해답은, **vcvarsall.bat을 실행시켰던 cmd창을 닫지 않고 그대로 bubblit 폴더로 이동해서 mix deps.compile을 해야 함**. 영구적인 설정 저장이 아니라, 일시적으로 저장하는 거 같음.

 일단 당장은 문제가 없는데, 매번 이렇게 해야 하는 건 아닐 거라고 믿고 있음...
그리고 왜 nmake로만 하라고 한 건지 모르겠음. 리눅스에서 그냥 되는거 보면 make로 그냥 하는 거 같고, 윈도우도 make 깔 수 있는데...

**Comment by pula39** [comment]
@RE-A 미안 준호야 다음부턴 세팅 열심히 쓸게.... 안닫고 그 상태에서 하는게 마자...

**Comment by pula39** [comment]
추후과제
 - 세션은 뭐고 토큰은 뭐냐...
 - 세션에 user_id 저장하고 plug에서 그걸로 로그인하던데 그러면 user_id만 있으면 로그인할수있는건가? 이거에 대한 확인이 필요
 - Process는 뭐하는 친굴까... Agent로 다 될거같은데
 - 그러나 Agent는 call이라는 점! 추후에는 cast로 바꿔야하는데 이거에 대한 생각은 에헤라 모르겠다

**Comment by pula39** [comment]
추후 과제 분리. 나머지는 잘 안함!!!!!!!!!!!!!!!!!
