### ISSUE TITLE
#23 작업 by Kynel

### ISSUE THREAD

**Issue by Kynel** [Capstone-R-99/BubbLit#26]
- [ ] 채팅로그 깔끔하게 보여줌
- [x] 공유스페이스 드래그로 크기 조정?
- [x] 탭 구현 (내부는 채팅로그 빼고 임시로)

추가사항
- [x] 모듈 리팩토링
- [ ] 합치기
- [ ] 기획더생각

**Comment by Kynel** [comment]
나중에 오른쪽 채팅영역에서 사용하면 좋을듯한 라이브러리
react-draggable
https://www.npmjs.com/package/react-draggable

**Comment by pula39** [comment]
> 채팅로그 깔끔하게 보여줌

이번주에 진행

 > 기획 더 생각
 > 합치기

평소에 하는 생각

닫습니다
