### ISSUE TITLE
회의를 진행할 때, 정보량에 따라 노출시간을 조절하는 방법

### ISSUE THREAD

**Issue by Kynel** [Capstone-R-99/BubbLit#3]
안녕하세요
회의를 시작하겠습니다
오늘 식사 메뉴는 무엇으로 할까요? 

와 같은 한 화자의 연속적인 발언시, 직전의 채팅을 노출하는 방법에 대한 고안이 필요

**Comment by RE-A** [comment]
나는

> 안녕

> 안녕
> 하세요

> 안녕
> 하세요
> 여러분

과 같이, 짧고 빠르게 올라오는 거면 말풍선 하나에 합치는 것도 괜찮을 것 같음.

**Comment by Kynel** [comment]
스크롤 기능으로 구현함
