### ISSUE TITLE
#32 채팅공간 할일 정리

### ISSUE THREAD

**Issue by Kynel** [Capstone-R-99/BubbLit#35]
- [x] Store에 state 지정
- [x] Action, 그에 따른 할 일 지정
- [x] 풍선안에 채팅모듈 집어넣기
- [x] (할수있으면) 서버통신 프로토타입보고 해봄
- [x] 풍선 두개 구별(채팅풍선, 유저풍선)
- [ ] 유저명 설정, 채팅박스에 뜨게 ( 이건 할수있을지 잘 모르겟다)
- [x] 채팅 입력창 어캐할지 생각해서 구현
- [ ] 유저풍선 안에 css로 다듬기
- [x] 코드 리팩토링
~~- [ ] 로비의 방 정보에 최대인원/현재인원 제대로 구현~~
-----------------------------------------------------------------------
- [x] 채팅풍선의 유지시간 구현
- [x] 말풍선 안의 채팅풍선 최대갯수 구현
- [x] 말풍선크기조절의 최대,최솟값 구현
- [x] 추후 퍼센티지, 비율 둘 다로 기획이 바뀔 수 있기 때문에 이 점 염두해서 구현
- [ ] 기타옵션? 뭐넣지? 생각만 해둘까?
- [x] 말풍선에 채팅풍선이 추가되면 뭔가 비주얼적인 Alert를 줘보고 이게 체크박스로?

-----------------------------------------------------------------------
### 추가사항
- [ ] 테마&UI 라이브러리 찾아 적용
- [ ] 새 메세지시 알림음
- [x] 새 메세지시 강조표시

**Comment by Kynel** [comment]
![image](https://user-images.githubusercontent.com/47177212/80294157-6445c580-87a1-11ea-9b2f-10f384d94eb0.png)
for문 안에서 index 받아서 쓸거면 let으로 선언하자.... 맨날이러면 안된다 이놈아

**Comment by pula39** [comment]
#52 로 이관
