### ISSUE TITLE
방에 7명 이상 들어간 기록이 있으면 방 로드에 실패

### ISSUE THREAD

**Issue by pula39** [Capstone-R-99/BubbLit#46]
확인하기 위해 이렇게 바꿔봄

![image](https://user-images.githubusercontent.com/52481470/80555323-eab11000-8a0a-11ea-8533-06e953990cb4.png)

이런 문제가 있음
![image](https://user-images.githubusercontent.com/52481470/80555302-dbca5d80-8a0a-11ea-9d5c-bbcbafab8308.png)

방 인원 제한에 대한 정책이 정해져야 말끔히 해결할 수 있음. 그거와 별개로 에러 처리를 해야함

**Comment by RE-A** [comment]
해결함 ㅅㄱ
