### ISSUE TITLE
오른쪽 채팅스페이스의 채팅풍선 & 로그 구조에 대한 고찰

### ISSUE THREAD

**Issue by Kynel** [Capstone-R-99/BubbLit#47]
### 해야하는 내용

**채팅로그의 비주얼**
- 채팅풍선 옆쪽에 펼쳣다 접엇다 할 수 있는 채팅로그
- 지금 생각하기로는 그냥 카톡처럼 쭉 일렬로 제공해도 괜찮을거같음 or 그때 생각한 사용자별 위치 추가
- 채팅풍선은 말한후 일정시간지나면 싹 비워지게끔 ㅇㅇ
- 로그를 보려면 '로그'를 켜라? 이런느낌

### 해결한 내용

**현재구조**
- 각 채팅풍선이 개별적으로 렌더링됨
- 각 풍선에 맞는 데이터들이 미리 가공되고, 채팅풍선모듈은 단순히 보여주기만함
- 그러다보니 새 메세지가 왔을때의 이벤트를 구현하는데 필요이상의 수고가 든다는 생각이 듬

**생각한구조**
- 상위 컴포넌트에서는 단순히 history만 넘겨줌
- 각 채팅풍선에는 단순히 id만 전달함
- 각 채팅풍선에 id에 맞는 history의 채팅을 선별적으로 집어넣음
- 이러면 복잡하지 않게 여러 기능(새 메세지 도착시 스크롤다운)들을 넣을 수 있을것같음
- 추가적으로 귓속말이라든가 이런걸 구현하는것도 상당히 간단해짐

**Comment by Kynel** [comment]
구조에 관한건 해결함

**Comment by pula39** [comment]
할만큼 고찰하고 해결했으니 닫겠습니다.
