### ISSUE TITLE
4/29일 회의

### ISSUE THREAD

**Issue by Kynel** [Capstone-R-99/BubbLit#48]
**실사용 피드백?**
- [x] 애니메이션 + 음성 & 새로운 채팅에 대한 피드백?
- [ ]  User id -> 닉네임
- [x] 시간 지나면 알파값 20정도로 낮춰주기?
- [ ] 버블끼리 서로 겹치지 않게, 블럭 최적화

**일요일까지 할 TOPIC**
- [x] youtube 라이브러리 교체
- [ ] 탭에 브로드캐스팅한 정보 저장하기(새로 들어온사람에게 전달)
- [ ] 실행기록
- [x] 채팅영역 구조
- [ ] 채팅풍선 유저 id -> 닉네임
- [x] 채팅풍선속 채팅 사라지게(일정시간 지나면)
- [ ] 사진 업로드시, 백에서 다운을 받든 서버에 올리든 구현 + ctrl v 구현
- [x] 빈화면에서 채팅치면 chat Input으로 커서 가게
- [ ] 채팅 로그 쌓이게 + 보이게

**Comment by RE-A** [comment]
이미지 공유 파트에서 클립보드로 복사한 데이터를 붙여넣기 해서 받아야 하는데, 이게 지금 잘 안됨.

* 일단, 데이터를 클립보드로 복사하는 라이브러리는 엄청나게 많음. 근데 클립보드->웹으로 가져오는 라이브러리는 거의 없고 그나마 찾은 게 `@charliewilco/gluejar` 라는 라이브러리인데, 이건 https://react-gluejar.now.sh/ 이런식으로 붙여넣기가 되긴 함. 

*  그런데 이 라이브러리는 소스코드를 까보니까 이미지 데이터를 받아오는게 아니라, 단순히 로컬에서 해당 파일의 경로(클립보드에 저장되어 있으니까 임시 경로로 컴퓨터 어딘가에 있겠지?)를 띄워주는 형식이라 해당 이미지 데이터(blob)을 직접 다룰 수 없음.

*  클립보드에서 데이터를 직접 가져오기로 했음.  코드는 다음과 같음.
```javascript

    handleImagePaste(e) {
        console.dir(e.clipboardData.items)
        let blobfile = e.clipboardData.items[0]
        console.log(typeof (blobfile))
        console.log(blobfile)
    }

    render() {
        return (
            <div className="sharespace-tab">
                <input
                    className="input"
                    onChange={this.handleImageUrlInput.bind(this)}
                    onPaste={this.handleImagePaste.bind(this)}
                />
                <button onClick={this.handleImageUrlClick.bind(this)}>이미지 변경</button>
            </div>
        )
    }
```
문제는, 클립보드에 뭘 복사해도 데이터가 항상 안 받아짐(empty list로 나옴). 
클립보드엔 정상적으로 저장되는거 확인했음. 
윈도우키+v로 클립보드에 저장되어 있는거 확인할 수 있음.
일단 참고: https://ko.reactjs.org/docs/events.html#clipboard-events

**Comment by pula39** [comment]
남은건 #52에서 계속합니다
