### ISSUE TITLE
4월 8일 발표를 위해 멘토 피드백을 적용한다.

### ISSUE THREAD

**Issue by pula39** [Capstone-R-99/BubbLit#5]
![image](https://user-images.githubusercontent.com/52481470/78498346-7a093180-7785-11ea-9ca4-2d0537b3b38a.png)

너무나 도움이 되는 피드백이 왔다.

## 메일 요점
 - 뭐가 새로운지 잘 모르겠다
    - 그래서 `아무래도 새로운것을 만들지 못한거같은데` 라는 전제 하에서 이야기가 나온다.
 - 새로운것으로, 참신하게 보이는 방법에는 `기존의 방법을 변형해 융합`이 있으니 해보면 어떤가?
    - 이런 접근방법으로 브레인스토밍 해봐라

## 메일에서 들은 시나리오 예시
 - 기존 회의 시스템에는 `의장`, `발언권 신청`, `회의 기록`이 있다.
 - 이런 특성을 도입하는 시나리오를 생각해봐라

## 우린 뭘 할 수 있죠?
 - 시나리오 예시가 괜찮음.
 - 나는 `발언권 신청`을 사실 시스템적으로 제어하지 않고 자율에 맡긴다 생각했음. 여러 사람이 말을 하면 자연스럽게 혼란스러우니까, 기존 회의처럼 채팅 주도자가 발언권을 조절하지 않을까 하는 마음.
 - 이를 시스템화 하면 좋을거 같다.

 ## 좀더 구체적으로 해봐라
 - 방 설정에서는 `엄격한 회의 모드`를 킬 수 있음
 - 이 모드에서는 방장이 `발언제한모드`를 킨 후, 발언권을 가지는 사람을 선택할 수 있음.
 - `발언제한모드`를 키지 않으면 기본이랑 똑같음. `발언제한모드`를 킨 후에는 다르다. 

|               | 발언권 O       | 발언권 X          |
|:---------------:|:----------------:|:-------------------:|
| 말풍선 크기   | 큼             | 작음              |
| 투명도        | 불투명(잘보임) | 반투명(잘 안보임) |
| 사운드 리액션 | 있음           | 없음              |

나름 정리해둠.

**Comment by RE-A** [comment]
혹시 여기서 추가할 사항 있으면 더 붙여보고, 없으면 일단 이 내용 정리해서 내일 저녁에 다시 메일 보내겠음.

**Comment by Kynel** [comment]
PPT 프로토타입에 일단 이내용을 정리하여 올려두고, 생각나는 내용있으면 붙이겠습니다.

**Comment by pula39** [comment]
적용했습니다. 끝!
