### ISSUE TITLE
룸과 유저의 관계

### ISSUE THREAD

**Issue by pula39** [Capstone-R-99/BubbLit#54]
이 일감은 정리가 되면 Wiki로 옮기고, 구현 일감으로 분리한 후 닫습니다

## 룸과 유저의 관계

 - 룸의 유저 입장 관련 규칙
   - 접속을 위한 비밀번호 설정
   - 링크 공개 설정 (링크를 공개하면 앱의 오픈리스트에 나온다.)
   ps. 링크 비공개를 하면, 자동으로 비밀번호를 사용하게 한다. (방 링크에 param으로 저장해서?)

 - 룸에서 가지고 있는 유저 관련 영속적인 정보
   - 지금 룸에 '속해있는' 유저
   - 이때까지 룸에 '속해있던' 유저 (관련 정보 렌더를 위해 필요함)
     - 결국 합쳐서 보내줘야하나?

 - 유저의 상태
   - 방에 속해있는지의 여부
   - 방에 접속해있는지의 여부

 - 방에 유저가 속하는 방법
   - Capacity가 남아있는 방에 들어간다
   - 먼저 들어간 사람이 임자!
   - 원하는 사람만 들어오고 싶어요!
     - 비번을 거세요

 - 속해있는 유저가 나가지는 방법
   - 자신이 방 설정에서 나간다 한다
   - 방장이 강퇴한다.

**Comment by pula39** [comment]
작업용 플로우를 짠다
 - [ ] Room DB를 수정해서 현재 있는 사람들을 저장하기 위한 칼럼을 만든다.
 - [ ] Channel 접속 시 인원 정보를 봐서 접속을 거부할 수 있게 한다.
 - [ ] 접속하자마자 새로운 유저면 DB에 등록하게 한다. 그리고 Front에 뜨게 한다.
 - [ ] Presence에 접속정보를 동기화 해서 프론트에 잘 내려준다

 - 나가는건 일단 미구현...

**Comment by RE-A** [comment]
관계 잘 이어나가고 있어서 닫음
