### ISSUE TITLE
blob 관리

### ISSUE THREAD

**Issue by pula39** [Capstone-R-99/BubbLit#60]
https://github.com/Capstone-R-99/BubbLit/issues/48#issuecomment-623123604

**Comment by pula39** [comment]
@RE-A 더 할게 있을까요?

**Comment by RE-A** [comment]
@pula39 gif가 움직이지 않는데, 아마 확장자가 지정되지 않아서 그런 것 같음. blob에서 이미지 확장자까지 알아내는 건 좀 힘들...겠지?

**Comment by RE-A** [comment]
일단 받아는지니까 Close
