### ISSUE TITLE
리팩토링 관련 

### ISSUE THREAD

**Issue by pula39** [Capstone-R-99/BubbLit#66]
![image](https://user-images.githubusercontent.com/52481470/81507892-5ebcb380-933b-11ea-9dda-d3daf8c4411b.png)

@Kynel INSERT_HISTORY라서 새로 추가하나 싶었더니 덮어씌우네요. 이름을 `UPDATE_HISTORY`나(덮어씌울거면) `APPEND_HISTORY`(추가할거면)로 바꾸는게 좋을 것 같습니다.

**Comment by pula39** [comment]
중간 데모 끝나고 바로 기술부채 없애야됨. 우려하던 일이 일어나는 중. store에 들어갈 데이터를 ChatModule에서 조합하고 있어서 문제가 크다. ChatModule은 최소 필요한 데이터만을 store에 넘겨주고, store에서 그 값을 이요해서 로직을 실행하게 해야함.
주로 이걸 쓰는 함수에서 그런 현상이 일어나고 있음. 3시간은 잡아야할듯 ㅎ...
```
    // chatTestModule 함수 가져와서 사용
    addMessageInChanges(changes, user_id, msg) {
        let notInChanges = (changes.hasOwnProperty('participants') && (changes['participants'].includes(user_id)) == false);
        if (notInChanges) {
            changes.participants = changes.participants.concat(user_id)
        }

        let find_user_id = (element) => {
            return element == user_id
        }

        if (msg == null) {
            return;
        }
        // if (modified_contents[user_idx].length >= 5) {
        //     //스크롤바 테스트를 위해 잠시 지워둠
        //     //modified_contents[user_idx].shift();
        // }

        let user_idx = changes.participants.findIndex(find_user_id)
        let modified_contents = changes.contents;
        changes.contents[user_idx] = modified_contents[user_idx].concat(msg)
    }

**Comment by pula39** [comment]
![image](https://user-images.githubusercontent.com/52481470/81508450-2a4af680-933f-11ea-88b8-a8ef530dfa9f.png)
f669d0438150b08e736d07f052543ae82163462a
history 나중에 탭 액션도 들어가야되서, + 애초에 필요없는 정보도 지금 같이 저장되서, 수정해야함. 

![image](https://user-images.githubusercontent.com/52481470/81508460-3d5dc680-933f-11ea-9a45-b0af31df89b8.png)

이거랑 같이 수정 이루어져야함

**Comment by Kynel** [comment]
> ![image](https://user-images.githubusercontent.com/52481470/81507892-5ebcb380-933b-11ea-9dda-d3daf8c4411b.png)
> 
> @Kynel INSERT_HISTORY라서 새로 추가하나 싶었더니 덮어씌우네요. 이름을 `UPDATE_HISTORY`나(덮어씌울거면) `APPEND_HISTORY`(추가할거면)로 바꾸는게 좋을 것 같습니다.

요거는 기존 객체에 삽입만하면 이뮤터블 이슈인지 제대로 업데이트가 안되더군요
그래서 새 객체 만들어서 거기에 끼워 넣고, 그 객체를 action.history로 받아오는 부분입니다.
그래서 덮어씌우는 식으로 구현하였는데, 이 방법에 문제가 있나요?

**Comment by pula39** [comment]
@Kynel 
댓글 단 첫번째 이유는 하는 일(history를 변경해서 스토어에 Update)과 action type(`INSERT_HISTORY`)의 이름이 맞지 않은 거였습니다.
그래서 기존방식처럼 history를 아에 새걸로 바꿔줄거면 `UPDATE_HISTORY` 등의 이름으로 바꾸는게 좋다 보았습니다.

그러나 스토어의 값을 가져와서 그걸 변형해서 스토어에 적용하는것보다는, 스토어에 변경에 필요한 데이터만 넘기고 변경 작업은 스토어에서 처리하는게 좋을거같습니다. 따라서 `APPEND_HISTORY`로 한 다음, 추가할 HISTORY만 스토어에 넘기고 스토어에서 HISTORY를 변경하는게 맞을 것 같습니다.

**Comment by Kynel** [comment]
@pula39 고렇군요

**Comment by Kynel** [comment]
@RE-A 일단 style을 자바스크립트 안에서 만져주고 있는데, 중간데모 끝나고 클래스이름 규칙 정해서 깔꼼하게 한번에 싹 빼놓겠습니다!

**Comment by RE-A** [comment]
중간 데모용으로 그럴듯하게 만드는 작업 중

**Comment by Kynel** [comment]
history는 나중에 탭히스토리 들어오면 구조를 생각해서 같이 처리할 예정임돠.
