### ISSUE TITLE
UI 프로토타입 제작

### ISSUE THREAD

**Issue by Kynel** [Capstone-R-99/BubbLit#7]
**TODO**

- [x] 방 선택 UI
- [x] 받아온 방 정보로 방 표시.
- [x] 채팅 입력하면 어떻게든 표시되게.

**설계**
- 우선, SPA 형태로 제작 후, React Router를 접목하여 URL에 따른 페이지 이동을 구현할 예정

**컴포넌트**
Board - mode(state)를 이용하여 Lobby, Room 으로의 이동을 구현한다 (추후 React Router로 대체)
Lobby - Store에서 받아온 state정보들로, 방을 생성한다.
Room - Store에서 받아온 state정보들로, 채팅을 구현한다.

**Comment by pula39** [comment]
![image](https://user-images.githubusercontent.com/52481470/79043325-6fddac00-7c39-11ea-8675-105bde011326.png)
프로토타입이 만들어져씀
