### ISSUE TITLE
이미지 공유시 확장자(타입) 체크 

### ISSUE THREAD

**Issue by RE-A** [Capstone-R-99/BubbLit#74]
gif같은경우엔 gif라고 인식을 못해서 정지화면으로 나옴

**Comment by pula39** [comment]
gif 지원은 나중에 합시다!

@RE-A 동의하면 닫기 ㄱㄱ

**Comment by RE-A** [comment]
클립보드에서 복사하는 특성상 기술적으로 불가능.
굳이 한다면 파일업로드로 이뤄져야 하는데 너무 코스트가 높아서 일단 계획에 없음.
참고로 디스코드도 이거 지원못함 ㅎㅎ
