### ISSUE TITLE
5월 13일 중간데모 피드백 정리

### ISSUE THREAD

**Issue by pula39** [Capstone-R-99/BubbLit#83]
### 자잘한 거
 - [x] 사람 많이 들어갈때 (아마 6명?) 버그 있었음.

 - [x] 직접회의 사용 -> 부족한점 찾기
 - [x] 링크, 이미지 저장?
 - [x] 강퇴, 방삭제 기능
 - [x] 자기가 들어있는 채팅방 표시

 ### 교수님 피드백
   - 중간에 들어온 사람들을 위한 기능을 추가. 이전으로 돌려볼 수 있는 기능을 만들어라 (기능 히스토리)
      - 이미지, 유튜브 실행기록 남냐고 그래서 물어봄
   - 제어권 잡아라
     - 많은 사람들이 마구잡이로 바꾸면 혼란스럽다.

### 조교님 피드백
   - [x] 실제 회의를 하면서 (개밥먹기) 필요한 기능을 찾아보는 것이 좋을듯.
   - [x] 방에 관한 다양한 기능
     - 방 나가고, 누가 만들었고, 주인 누구고, 다 나가면 어떻게 되냐

### 유튜브 추가기능 건의
   - [x] 일시정지 연동
   - [x] 탭 이동시 소리 뮤트 기능?

**Comment by RE-A** [comment]
- [ ] gif 지원도 추가

**Comment by pula39** [comment]
할만큼 했으니 이슈를 닫습니다.
