### ISSUE TITLE
기본 채팅방 + 채팅 기능 구현

### ISSUE THREAD

**Issue by RE-A** [Capstone-R-99/BubbLit#9]
- [x] 채팅 기능 테스트용 프론트엔드 모듈 작성
- [ ] 참가자 목록 표시(내가 지정한 ID가 아니라도, 현재 접속한 사람들을 구별할수만 있으면 상관 없음)
- [x] 여러명 동시 채팅 기능 구현
- [x] 채팅방 입장/퇴장 구현

- [ ] 채팅 모듈 문서화

**Comment by pula39** [comment]
![image](https://user-images.githubusercontent.com/52481470/79043332-7cfa9b00-7c39-11ea-978d-054d2db7208b.png)
문서화 빼고 다해씀
