### ISSUE TITLE
12주차 임시데모용 준비

### ISSUE THREAD

**Issue by RE-A** [Capstone-R-99/BubbLit#95]
## 발표 포인트
 - [ ] (구현의 최종목표가) 뭘 목표로 삼고 있는지
 - [ ] 지금 무엇이 미흡한지 따라서 어떤걸 개선해야겠다를 중점적으로 발표
 - [ ] 당연히 지금까지 된것도 보여줘야함

#### 로비 기능
  - [x] 내가 들어가있는 방
  - [x] 6명 이상인 방 못들어가게하기
  - [ ] 현재인원/ 접속인원 등 숨겼던 기능 다 제대로 보여주기
#### 기능 히스토리 보여주기
   - [x] 쭉 보여주기만 한다
#### 채팅 히스토리 보여주기
   - [x] 쭉 보여주기만 한다
#### 리팩토링
- [x] ENTER_CHAT 이름 바꾸고 로직 간단하게 하기

#### 방 기능
- [ ] 아예 방 나가기 기능 추가

**Comment by pula39** [comment]
뭘 목표?
 - 최종 목표의 포인트
    - 즐길 수 있는 공간 -> 어느정도 만족
    - 같은 화면 공유 -> 이미지, 영상 쉐어기능
    - 그러면서, 채팅의 기본 요건 충족 (히스토리 기능)
    - 학과 개발지식의 도입 -> 개발론

 - 미흡한거 
   - 채팅의 기본요건
      - 내가 속한 채팅방 
      - 채팅방이 많아졌을 때의 처리
      - 그래서... 비밀채팅방 (비밀번호, 특정링크를 통한 입장) 
   - 기능이 조금 부족하다
      - 커스텀 탭 (유저가 올릴 수 있는 url)
   - 경험이 불친절
      - 로비 페이지네이션
      - 내가 속한방 표시방식 개선 (방이 많아지면 파악하기 힘드므로) 맨 위로 올리기
      - 채팅 히스토리는 기존으로 문제 없다 판단. 기능 히스토리에 집중.
      - 이미지 이전꺼 보기 (^^)

내일 PPT 를 만들거고
만들면 디코에 말함. 
화요일에 만나자
화요일 9시에 만나서 데모. 끝!

**Comment by RE-A** [comment]
맞다 방 아예 나가기 기능 추가해야함

**Comment by pula39** [comment]
임시데모를 잘 마쳤기에 닫습니다
